# rake tasks - think of these like npm run scripts
# helper tasks to automate common dev tasks

require "rubygems"
require "active_record"
require "yaml"

desc "load the environment"
task :environment do
  env = ENV["SINATRA_ENV"] || "development"
  databases = YAML.load_file("config/database.yml")
  ActiveRecord::Base.establish_connection(databases[env])
end

namespace :db do
  desc "Migrate the database"
  task(migrate: :environment) do
    ActiveRecord::Base.logger = Logger.new($stdout)
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.migrate("db/migrate")
  end
end
